# PYTHON LIBRARY FOR NUMERICAL COMPUTATION: NumPy

In [2]:
import numpy as np


# print the numpy version and the configuration

In [3]:
print(np.__version__)
#np.show_config()

1.13.3


# create a null vector of size 10 but the fifth value is 1

In [4]:
z=np.zeros(10)
z[4]=1
print(z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


# create a vector with values ranging from 10 to 49

In [5]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# reverse a vector(first element becomes last )

In [6]:
z=np.arange(50)
z=z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


# create a 3x3 matrix with values ranging from 0 to 8

In [7]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# find indices of non-zero elements from [1,2,0,0,4,0]

In [9]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int32),)


# create a 3x3 identity matrix

In [10]:
z=np.eye(3)
print(z)     # in the output dot is there c0z by default data type is float

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# create a 3x3x3 array with random values

In [3]:
z=np.random.random((3,3,3))
print(z)

[[[ 0.50846316  0.81307478  0.88363155]
  [ 0.79128761  0.1777589   0.2890009 ]
  [ 0.96743466  0.50669244  0.1816867 ]]

 [[ 0.46137689  0.06497152  0.85699076]
  [ 0.69735691  0.92214171  0.13924761]
  [ 0.53920939  0.47275176  0.11012224]]

 [[ 0.0587806   0.50153474  0.03998681]
  [ 0.92289547  0.68606637  0.62140567]
  [ 0.43182827  0.8604473   0.22598462]]]


# create a 10x10 array with random values and find the minimum and maximum value

In [14]:
z=np.random.random((10,10))
zmin,zmax=z.min(),z.max()
print(zmin,zmax)

0.00524460620789 0.987343557249


# create a random vector of size 30 and find the mean value

In [15]:
z=np.random.random(30)
m=z.mean()
print(m)

0.538828981408


# create a 2d array with 1 on the border and 0 inside

In [18]:
z=np.ones((10,10))
print(z)
z[1:-1,1:-1]=0
print(z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


# create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [21]:
p=1+np.arange(4)
print(p)
z=np.diag(1+np.arange(4))    # diag specifies that diag elements should be inc by 1
print(z)

[1 2 3 4]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# create a checkerboard 8x8 matrix using the tile function

In [23]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))   # tile used for repetition
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# normalize a 5x5 random matrix

In [25]:
z=np.random.random((5,5))
zmax,zmin=z.max(),z.min()
z=(z-zmin)/(zmax-zmin)
print(z)

[[ 0.25761687  0.61276713  0.          0.81974921  0.88808174]
 [ 0.03128077  0.18398323  0.78599894  0.85059797  0.46023359]
 [ 0.73317494  0.48347587  0.29112619  0.80080359  0.74309027]
 [ 0.77650461  0.48703451  0.63249889  0.21337714  0.59109736]
 [ 0.57590862  0.48549988  1.          0.17103981  0.96257841]]


# multiply a 5x3 matrix by a 3x2 matrix(real matrix product)

In [26]:
z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


# extract the integer part of a random array using 5 different method

In [29]:
z=np.random.uniform(0,10,10)
print(z)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[ 0.8349764   7.24695171  7.94295256  1.61876999  1.83989767  4.73384058
  0.69780118  6.96782515  9.20643751  5.86949346]
[ 0.  7.  7.  1.  1.  4.  0.  6.  9.  5.]
[ 0.  7.  7.  1.  1.  4.  0.  6.  9.  5.]
[ 0.  7.  7.  1.  1.  4.  0.  6.  9.  5.]
[0 7 7 1 1 4 0 6 9 5]
[ 0.  7.  7.  1.  1.  4.  0.  6.  9.  5.]


# create 5x5 matrix with row values ranging from 0 to 4

In [30]:
z=np.zeros((5,5))
print(z.shape)
print(z)
z+=np.arange(5)
print(z.shape)
print(z)

(5, 5)
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
(5, 5)
[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


# create a vector of size 10 wth values ranging from 0 to 1,both excluded

In [31]:
z=np.linspace(0,1,12,endpoint=True)[1:-1]
print(z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


# create a vector of size 10 and sort

In [32]:
z=np.random.random(10)
z.sort()
print(z)

[ 0.04897542  0.0524528   0.07360788  0.11260605  0.12182006  0.16528979
  0.20936123  0.21324166  0.21665393  0.43121208]


# create a random vector of size 10 and replace the maximum vakue

In [33]:
z=np.random.random(10)
print(z.argmax())    # returns the index of max value
z[z.argmax()]=0
print(z)

2
[ 0.59994489  0.00116696  0.          0.94465418  0.64754948  0.20750607
  0.22416391  0.49395936  0.80992815  0.85057929]


# subtract the mean of each row of a matrix

In [37]:
x=np.random.rand(5,10)
y=x-x.mean(axis=1,keepdims=True)
print(y)

[[ 0.36162077  0.13087934 -0.36464124  0.2125804   0.30085025 -0.45530104
   0.50871671 -0.35882124 -0.19412118 -0.14176277]
 [ 0.11924881  0.05086844  0.0051117   0.14173349 -0.14958751 -0.16966005
  -0.04552835 -0.12232512  0.16486768  0.00527091]
 [-0.24263528 -0.29644401 -0.48212317  0.29847915  0.27344792  0.37406733
   0.05646584  0.2935949   0.13883385 -0.41368653]
 [-0.52124521 -0.33068779  0.20429839  0.23056072  0.38238792  0.06120258
   0.24594489 -0.03680447  0.11135536 -0.34701239]
 [-0.3237315  -0.1192078  -0.14201082 -0.16657097  0.2731806   0.53034625
  -0.1853871  -0.07115341 -0.22207318  0.42660794]]


# how to sort an array by the nth column

In [5]:
z=np.random.randint(0,10,(3,3))
print(z)
print(z[:,1])
print(z[z[:,2].argsort()])

[[4 2 5]
 [0 1 8]
 [0 5 0]]
[2 1 5]
[[0 5 0]
 [4 2 5]
 [0 1 8]]


# find indices of non-zero elements from [1,2,0,0,4,0]

In [6]:
vector1=np.array([1,2,3,4,5,6])

In [7]:
vector1.shape  # attribute which gives the length .....i.e.returns in tuple form(also it shows that it is 1d array)

(6,)

In [8]:
v1=vector1.reshape(1,6)
v1.shape

(1, 6)

# create row and column vectors

In [9]:
vector2=np.array([[1,2,3,4],[3,4,5,6]])   # row
print(vector2)
print(vector2.shape)

[[1 2 3 4]
 [3 4 5 6]]
(2, 4)


In [12]:
vector3=np.array([[1],[2],[3]])      # column
print(vector3) 
print(vector3.shape)

[[1]
 [2]
 [3]]
(3, 1)


# select second element

In [13]:
print(vector3[1])

[2]


In [14]:
print(vector2[0])

[1 2 3 4]


# multi-dimensional arrray known as matrix can be obtained using the syntax given below

# matrix elemnts are accessed by row and column number

In [15]:
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [16]:
print(matrix[0])

[1 2 3]


In [17]:
print(matrix[0][1])

2


In [18]:
print(matrix[0,1])

2


In [19]:
print(matrix[0,:])
print(matrix[1,:])
print(matrix[:,1])

[1 2 3]
[4 5 6]
[2 5 8]


In [20]:
# view number of elements(row*columns)
matrix.size

9

In [21]:
# view number of dimensions (1d or 2d or 3d array)
matrix.ndim

2

In [22]:
# return variance
np.var(matrix)

6.666666666666667

In [23]:
# return mean
np.mean(matrix)

5.0

In [24]:
# return standard deviation
np.std(matrix)

2.5819888974716112

In [25]:
# return diagonal elemnts
matrix.diagonal()

array([1, 5, 9])

In [26]:
# return maximum elemnts
np.max(matrix)

9

In [27]:
# return min element
np.min(matrix)

1

In [28]:
# find the maximum elemnt in each column
np.max(matrix,axis=0)  # axis 0 for column

array([7, 8, 9])

In [30]:
# find the maximum elemnt in each row
np.max(matrix,axis=1)  # axis 1 for row

array([3, 6, 9])

In [31]:
# operations requires the linear algebra routine of NumPy

In [32]:
# return determinant of matrix
np.linalg.det(matrix)

6.6613381477509402e-16

In [33]:
# return matrix rank
np.linalg.matrix_rank(matrix)

2

# Vector and Matrix Manipulation

In [34]:
# flatten matrix
matrix.ravel()   # converts into 1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# flatten matrix
matrix.flatten()    #converts into 1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# reshape matrix into 1x9 matrix
matrix.reshape(1,9)    #converts into 1d

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [37]:
# reshape matrix into 9x1 matrix
matrix.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [38]:
# reshape matrix into 3x3x1 matrix
matrix.reshape(3,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [40]:
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# hstack/vstack:Horizontal and vertical stacking means the arrays are positioned horizontally or vertically to the first array and so on.

In [41]:
array1=np.array([[1,2,3,4]])
print(array1)
array2=np.array([[5,6,7,8]])
print(array2)
d=np.vstack((array1,array2))
d.shape

[[1 2 3 4]]
[[5 6 7 8]]


(2, 4)

In [42]:
array1=np.array([[1,2,3,4]])
print(array1)
array2=np.array([[5,6,7,8]])
print(array2)
h=np.hstack((array1,array2))
h.shape

[[1 2 3 4]]
[[5 6 7 8]]


(1, 8)

# Arithmetic operations

In [43]:
# create matrix
matrix_a=np.array([[1,1,1],
                  [1,1,1],
                  [1,1,2]])
# create matrix
matrix_b=np.array([[1,2,1],
                  [1,3,1],
                  [1,3,8]])

In [44]:
np.add(matrix_a,matrix_b)

array([[ 2,  3,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [45]:
np.subtract(matrix_a,matrix_b)

array([[ 0, -1,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [46]:
np.multiply(matrix_a,matrix_b)

array([[ 1,  2,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

In [47]:
np.divide(matrix_a,matrix_b)


array([[ 1.        ,  0.5       ,  1.        ],
       [ 1.        ,  0.33333333,  1.        ],
       [ 1.        ,  0.33333333,  0.25      ]])

In [48]:
np.exp(matrix_a)

array([[ 2.71828183,  2.71828183,  2.71828183],
       [ 2.71828183,  2.71828183,  2.71828183],
       [ 2.71828183,  2.71828183,  7.3890561 ]])

In [49]:
np.sqrt(matrix_b)

array([[ 1.        ,  1.41421356,  1.        ],
       [ 1.        ,  1.73205081,  1.        ],
       [ 1.        ,  1.73205081,  2.82842712]])

In [50]:
np.sin(matrix_a)

array([[ 0.84147098,  0.84147098,  0.84147098],
       [ 0.84147098,  0.84147098,  0.84147098],
       [ 0.84147098,  0.84147098,  0.90929743]])

In [51]:
vector_a=np.array([1,2,3])
vector_b=np.array([4,5,6])
#calculate the dot product
np.dot(vector_a,vector_b)

32